version: "3"

services:
  app:
    build: ./Dockerfile.prod
    platform: linux/amd64
    restart: always
    container_name: "daily-diet-backend"
    ports:
      - "3333:3333"
    command: npm run start:prod
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: "daily-diet-database"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "daily_diet_db_password"
      POSTGRES_DB: "daily-diet-db-postgres"
    ports:
      - "3003:5432"
volumes:
  pgdata: